# galemp_xshowpos.py
#
# This file was autogenerated by Parrot's PytkBackend module

from Tkinter import *
from Dialog import Dialog


#/////////////////////////////////////////////////////////////////////

class XShowPos(Frame):

   def  __init__(self, parent=None):
      Frame.__init__(self, parent)
      self.pack()
      self.createMenuBar()
      self.createGUI()
      self.master.title("Show position")
      self.master.iconname("self")
 
   def createMenuBar(self):
      self.menubar = Frame(self, relief=RAISED, bd=2)
      self.menubar.pack(side=TOP, fill=X)

      #----- menu "File"
      mbutton = Menubutton(self.menubar, text='File', underline=0)
      mbutton.pack(side=LEFT)
      menu = Menu(mbutton, tearoff=N)
      menu.add_command(label='Open...', command=self.Open_pressed)
      menu.add_command(label='Exit', command=self.Exit_pressed)
      mbutton['menu'] = menu

      #----- menu "Edit"
      mbutton = Menubutton(self.menubar, text='Edit', underline=0)
      mbutton.pack(side=LEFT)
      menu = Menu(mbutton, tearoff=N)
      menu.add_command(label='Copy', command=self.Copy_pressed)
      menu.add_command(label='Cut', command=self.Cut_pressed)
      menu.add_command(label='Paste', command=self.Paste_pressed)
      mbutton['menu'] = menu

      #----- menu "Help"
      mbutton = Menubutton(self.menubar, text='Help', underline=0)
      mbutton.pack(side=LEFT)
      menu = Menu(mbutton, tearoff=N)
      menu.add_command(label='Help', command=self.Help_pressed)
      menu.add_command(label='About XShowPos...', command=self.About_pressed)
      mbutton['menu'] = menu

   def createGUI(self):
      par_rowLayout1 = Frame(self, relief=RIDGE, bd=4, bg='#eeee88')
      par_colLayout2 = Frame(par_rowLayout1, relief=RIDGE, bd=4, bg='#8888ee')
      par_label3 = Label(par_colLayout2, text="First column!")
      par_label3.pack(side=TOP, anchor=NW)
      but4 = Button(par_colLayout2, text="press me")
      but4.config(command=self.but4_pressed)
      but4.pack(side=TOP, anchor=NW)
      par_colLayout2.pack(side=LEFT, anchor=NW)
      par_colLayout4 = Frame(par_rowLayout1, relief=RIDGE, bd=4, bg='#8888ee')
      par_label5 = Label(par_colLayout4, text="Text here")
      par_label5.pack(side=TOP, anchor=NW)
      area = Text(par_colLayout4, height=10, width=40)
      area.insert("1.0", "look at my textarea!")
      area.pack(side=TOP, anchor=NW)
      par_colLayout4.pack(side=LEFT, anchor=NW)
      par_rowLayout1.pack(side=TOP, anchor=NW)
      par_rowLayout6 = Frame(self, relief=RIDGE, bd=4, bg='#eeee88')
      but1 = Button(par_rowLayout6, text="Button 1")
      but1.config(command=self.but1_pressed)
      but1.pack(side=LEFT, anchor=NW)
      but2 = Button(par_rowLayout6, text="Button 2")
      but2.config(command=self.but2_pressed)
      but2.pack(side=LEFT, anchor=NW)
      but3 = Button(par_rowLayout6, text="Button 3")
      but3.config(command=self.but3_pressed)
      but3.pack(side=LEFT, anchor=NW)
      bottomLabel = Label(par_rowLayout6, text="text at bottom label")
      bottomLabel.pack(side=LEFT, anchor=NW)
      par_rowLayout6.pack(side=TOP, anchor=NW)

#***** methods to be redefined

   def Open_pressed(self):
      print '[XShowPos Open_pressed]'      

   def Exit_pressed(self):
      print '[XShowPos Exit_pressed]'      

   def Copy_pressed(self):
      print '[XShowPos Copy_pressed]'      

   def Cut_pressed(self):
      print '[XShowPos Cut_pressed]'      

   def Paste_pressed(self):
      print '[XShowPos Paste_pressed]'      

   def Help_pressed(self):
      print '[XShowPos Help_pressed]'      

   def About_pressed(self):
      print '[XShowPos About_pressed]'      

   def but4_pressed(self):
      print '[XShowPos but4_pressed]'      

   def but1_pressed(self):
      print '[XShowPos but1_pressed]'      

   def but2_pressed(self):
      print '[XShowPos but2_pressed]'      

   def but3_pressed(self):
      print '[XShowPos but3_pressed]'      

#***** end of methods to be redefined

#/////////////////////////////////////////////////////////////////////

if __name__=='__main__':
   XShowPos().mainloop()

#/////////////////////////////////////////////////////////////////////

#(end galemp_xshowpos.py)
